version: "2"

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  db_admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db:db
    ports:
      - "8080:80"

  omeka:
    depends_on:
      - db
      - traefik
    build: ./
    volumes:
      - omeka-files:/var/www/html/files
    image: omeka
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omeka.rule=Host(`archivosdelsur.ar`)"
      - "traefik.http.routers.omeka.entrypoints=websecure"
      - "traefik.http.routers.omeka.tls.certresolver=myresolver"
      - "traefik.http.routers.omeka-redirect.entrypoints=web"
      - "traefik.http.routers.omeka-redirect.rule=Host(`archivosdelsur.ar`)"
      - "traefik.http.routers.omeka-redirect.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=infra@lawal.coop"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8082:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  mysql-data:
    driver: local
  omeka-files:
    driver: local
